/**
 * Generated by orval v8.0.0-rc.6 🍺
 * Do not edit manually.
 * juny-api
 * OpenAPI spec version: 0.1.0
 */

/**
 * Refresh token request.
 */
export interface RefreshTokenRequest {
  refresh_token: string;
}
